#!/usr/bin/env node
/*
	JSON-to-Go
	by Matt Holt

	https://github.com/mholt/json-to-go

	A backwards compatible integration of json-to-go-v2
*/

const jsonToGov2 = require('./json-to-go-v2')

// for backwards compatibility
function jsonToGo(json, typename = "AutoGenerated", flatten = true, example = false, allOmitempty = false) {
	return jsonToGov2(
		json,
		{
			typename: typename,
			flatten: flatten,
			example: example,
			allOmitempty: allOmitempty,
		})
}

if (typeof module === 'undefined' || !module.parent) {
	// being able to run json-to-go backwards compatible
	const vm = require('vm');
	const fs = require('fs');
	const jscode = fs.readFileSync('./json-to-go-v2.js');
	const context = {
		Buffer,
		console,
		process,
		require,
	};
	vm.runInNewContext(jscode, context);
}

if (typeof module !== 'undefined') {
	module.exports = jsonToGo
}
