type AutoGenerated struct {
	Booleanfield bool `json:"booleanfield"`
	Somearray []Somearray `json:"somearray"`
	Date string `json:"date"`
}
type Somearray struct {
	ID any `json:"id"`
	Name string `json:"name"`
	Features any `json:"features"`
}
