type AutoGenerated struct {
	AgeOfTheUniverse []AgeOfTheUniverse `json:"age of the universe"`
	AgeOfTheEarth []AgeOfTheEarth `json:"age of the earth"`
	Date string `json:"date"`
}
type AgeOfTheUniverse struct {
	Name string `json:"name"`
	Value float64 `json:"value"`
}
type AgeOfTheEarth struct {
	Name string `json:"name"`
	Value int64 `json:"value"`
}
