type AutoGenerated struct {
	Booleanfield bool `json:"booleanfield"`
	Somearray []Somearray `json:"somearray"`
	Date string `json:"date"`
}
type Features struct {
	Age int `json:"age,omitempty"`
	Height int `json:"height,omitempty"`
}
type Somearray struct {
	ID int `json:"id"`
	Name string `json:"name"`
	Features Features `json:"features"`
}
