type AutoGenerated struct {
	Booleanfield bool `json:"booleanfield"`
	Inconsistentarray []Inconsistentarray `json:"inconsistentarray"`
	Date string `json:"date"`
}
type Features struct {
	Age int `json:"age,omitempty"`
	Height any `json:"height,omitempty"`
	Gender string `json:"gender,omitempty"`
}
type Inconsistentarray struct {
	ID int `json:"id"`
	Name string `json:"name"`
	Features Features `json:"features"`
}
