type AutoGenerated struct {
	Region Region `json:"region"`
	Municipality Municipality `json:"municipality"`
	Building Building `json:"building"`
}
type RegionIdentifier struct {
	Type string `json:"type"`
	ID int `json:"id"`
}
type Region struct {
	RegionIdentifier RegionIdentifier `json:"identifier"`
	Autonomous bool `json:"autonomous"`
}
type MunicipalityIdentifier struct {
	Type string `json:"type"`
	Name string `json:"name"`
}
type Municipality struct {
	MunicipalityIdentifier MunicipalityIdentifier `json:"identifier"`
}
type BuildingIdentifierPostal struct {
	Type string `json:"type"`
	ID int `json:"id"`
}
type BuildingIdentifierRoad struct {
	Name string `json:"name"`
	ID int `json:"id"`
}
type BuildingIdentifier struct {
	BuildingIdentifierPostal BuildingIdentifierPostal `json:"postal"`
	BuildingIdentifierRoad BuildingIdentifierRoad `json:"road"`
}
type Building struct {
	BuildingIdentifier BuildingIdentifier `json:"identifier"`
}
