type AutoGenerated struct {
	Region Region `json:"region"`
	Municipality Municipality `json:"municipality"`
	Building Building `json:"building"`
}
type Identifier struct {
	Type string `json:"type"`
	ID int16 `json:"id"`
}
type Region struct {
	Identifier Identifier `json:"identifier"`
	Autonomous bool `json:"autonomous"`
}
type MunicipalityIdentifier struct {
	Type string `json:"type"`
	Name string `json:"name"`
}
type Municipality struct {
	MunicipalityIdentifier MunicipalityIdentifier `json:"identifier"`
}
type Postal struct {
	Type string `json:"type"`
	ID int8 `json:"id"`
}
type Road struct {
	Name string `json:"name"`
	ID int8 `json:"id"`
}
type BuildingIdentifier struct {
	Postal Postal `json:"postal"`
	Road Road `json:"road"`
}
type Building struct {
	BuildingIdentifier BuildingIdentifier `json:"identifier"`
}
