type AutoGenerated struct {
	Basedonscience bool `json:"basedonscience"`
	SecondsPerYear float32 `json:"seconds per year"`
	AgeOfTheUniverse AgeOfTheUniverse `json:"age of the universe"`
	BasicallyInfinity any `json:"basically infinity"`
	Date string `json:"date"`
}
type AgeOfTheUniverse struct {
	InPlanckTime float64 `json:"in planck time"`
	InVeryPreciseMilliseconds float64 `json:"in very precise milliseconds"`
	InMilliseconds float32 `json:"in milliseconds"`
	InSeconds int64 `json:"in seconds"`
	InYears int64 `json:"in years"`
	InMillenia int32 `json:"in millenia"`
	InMegaannums int16 `json:"in megaannums"`
	InGalacticYears int8 `json:"in galactic years"`
}
